use chromix_core::Ramp;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

pub fn write(path: &Path, name: &str, ramp: &Ramp) -> std::io::Result<()> {
    let file = File::create(path)?;
    let mut writer = BufWriter::new(file);

    writeln!(writer, "/* Generated by chromix. */")?;
    writeln!(writer, ":root {{")?;

    for entry in &ramp.entries {
        let oklch = entry.oklch.to_css();
        writeln!(writer, "  --{}-{}: {};", name, entry.step, oklch)?;
    }

    writeln!(writer, "}}")?;

    Ok(())
}
