use chromix_core::Ramp;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

fn js_key(name: &str) -> String {
    // Unquoted if valid JS identifier: non-empty, every char is _/ASCII-letter,
    // or an ASCII digit at position > 0 (no leading digit)
    let chars: Vec<char> = name.chars().collect();
    if chars.is_empty() {
        return format!("\"{}\"", name);
    }

    // First char must be letter or underscore
    if !chars[0].is_ascii_alphabetic() && chars[0] != '_' {
        return format!("\"{}\"", name);
    }

    // All chars must be letter, digit, or underscore
    for ch in &chars[1..] {
        if !ch.is_ascii_alphanumeric() && ch != &'_' {
            return format!("\"{}\"", name);
        }
    }

    name.to_string()
}

pub fn write(path: &Path, name: &str, ramp: &Ramp) -> std::io::Result<()> {
    let file = File::create(path)?;
    let mut writer = BufWriter::new(file);

    writeln!(writer, "/** Generated by chromix. Drop into your tailwind.config.js. */")?;
    writeln!(writer, "module.exports = {{")?;
    writeln!(writer, "  theme: {{")?;
    writeln!(writer, "    extend: {{")?;
    writeln!(writer, "      colors: {{")?;

    let key = js_key(name);
    writeln!(writer, "        {}: {{", key)?;

    for (i, entry) in ramp.entries.iter().enumerate() {
        let oklch = entry.oklch.to_css();
        let step = entry.step;
        let comma = if i < ramp.entries.len() - 1 { "," } else { "" };
        writeln!(writer, "          \"{}\": \"{}\"{}", step, oklch, comma)?;
    }

    writeln!(writer, "        }},")?;
    writeln!(writer, "      }},")?;
    writeln!(writer, "    }},")?;
    writeln!(writer, "  }},")?;
    writeln!(writer, "}};")?;

    Ok(())
}